
services:
  frontend:
    build: ./frontend
    container_name: pizza_frontend
    restart: always
    networks:
      - pizza_net

  backend:
    build: ./backend
    container_name: pizza_backend
    restart: always
    environment:
      - DB_HOST=${DB_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - pizza_net

  db:
    image: postgres:17-alpine
    container_name: pizza_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pizza_net

  nginx:
    image: nginx:alpine
    container_name: pizza_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.crt:/etc/nginx/certs/nginx.crt:ro
      - ./nginx/nginx.key:/etc/nginx/certs/nginx.key:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    networks:
      - pizza_net

  prometheus:
    image: prom/prometheus:latest
    container_name: pizza_prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.external-url=/prometheus/'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules.yml:/etc/prometheus/alert.rules.yml
    networks:
      - pizza_net

  grafana:
    image: grafana/grafana:latest
    container_name: pizza_grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - pizza_net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: pizza_node_exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - pizza_net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: pizza_cadvisor
    restart: always
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - pizza_net

  alertmanager:
    image: prom/alertmanager:latest
    container_name: pizza_alertmanager
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - pizza_net

networks:
  pizza_net:
    driver: bridge

volumes:
  postgres_data: