# 1. Редирект с HTTP на HTTPS
server {
    listen 80;
    server_name localhost;
    return 301 https://$host$request_uri;
}

# 2. HTTPS Сервер
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/certs/nginx.crt;
    ssl_certificate_key /etc/nginx/certs/nginx.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    auth_basic_user_file /etc/nginx/.htpasswd;

    # Frontend (без пароля)
    location / {
        auth_basic off;
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Backend API (без пароля)
    location /api/ {
        auth_basic off;
        proxy_pass http://backend:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Prometheus (с паролем)
    location /prometheus/ {
        auth_basic "Restricted Area";
        proxy_pass http://prometheus:9090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Alertmanager (с паролем)
    location /alertmanager/ {
        auth_basic "Restricted Area";
        proxy_pass http://alertmanager:9093/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Grafana (с паролем)
    location /grafana/ {
        auth_basic "Restricted Area";
        proxy_pass http://grafana:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}